---
  - hosts: a445
    vars:
      openntpd_ntp_servers: "timeserver.dcti.sut.ru"
        
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a445/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"

    - name: install packages for time sync
      action: apt name=openntpd state=installed
    
    - name: install packages for gss api auth to work
      action: apt pkg={{item}} state=installed install_recommends=no update_cache=no
      with_items:
        - libsasl2-modules-gssapi-mit
        - libncurses5:i386

    - name: Install openntpd config
      template: src=templates/etc_openntpd_ntpd.conf.j2 dest=/etc/openntpd/ntpd.conf
      notify: restart openntpd

    - name: Install openntpd defaults
      copy: src=files/a445/etc/default/openntpd dest=/etc/default/openntpd
      notify: restart openntpd
    
    - name: install common lisp
      action: apt name=clisp state=installed update_cache=no install_recommends=no

    - name: install swi prolog
      action: apt name=swi-prolog state=installed update_cache=no install_recommends=no

    - name: install doxygen
      action: apt pkg={{item}} state=installed install_recommends=no update_cache=no
      with_items:
        - doxygen
	- graphviz

    - include: tasks/addlocalrepo.yml

    - include: tasks/addemdebianrepo.yml

    - include: tasks/install_arm_toolchain.yml

    - include: tasks/fixxsessionerrors.yml

    - include: tasks/installvnc.yml

    - include: tasks/installrusersd.yml

    handlers:
    - name: restart openntpd
      service: name=openntpd state=restarted
  
  - hosts: a439
    vars:
      openntpd_ntp_servers: "timeserver.dcti.sut.ru"
        
    remote_user: root
    tasks:
    - name: install packages for time sync
      action: apt name=openntpd state=installed
    
    - name: install common lisp
      action: apt name=clisp state=installed update_cache=no install_recommends=no

    - name: install swi prolog
      action: apt name=swi-prolog state=installed update_cache=no install_recommends=no

    - name: install doxygen
      action: apt pkg={{item}} state=installed install_recommends=no update_cache=no
      with_items:
        - doxygen
	- graphviz
    
    - include: tasks/installjavatests.yml
    
  
  - hosts: a437
    vars:
      openntpd_ntp_servers: "timeserver.dcti.sut.ru"
        
    remote_user: root
    tasks:
    - name: install packages for time sync
      action: apt name=openntpd state=installed
    
    - name: install common lisp
      action: apt name=clisp state=installed update_cache=no install_recommends=no

    - name: install swi prolog
      action: apt name=swi-prolog state=installed update_cache=no install_recommends=no

    - name: install doxygen
      action: apt pkg={{item}} state=installed install_recommends=no update_cache=no
      with_items:
        - doxygen
	- graphviz
  
  - hosts: a443
    vars:
      openntpd_ntp_servers: "timeserver.dcti.sut.ru"
        
    remote_user: root
    tasks:
    - name: install packages for time sync
      action: apt name=openntpd state=installed
    
    - name: install common lisp
      action: apt name=clisp state=installed update_cache=no install_recommends=no

    - name: install swi prolog
      action: apt name=swi-prolog state=installed update_cache=no install_recommends=no

    - name: install doxygen
      action: apt pkg={{item}} state=installed install_recommends=no update_cache=no
      with_items:
        - doxygen
	- graphviz
  
  - hosts: a441
    vars:
      openntpd_ntp_servers: "timeserver.dcti.sut.ru"
        
    remote_user: root
    tasks:
    - name: install packages for time sync
      action: apt name=openntpd state=installed
    
    - name: install common lisp
      action: apt name=clisp state=installed update_cache=no install_recommends=no

    - name: install swi prolog
      action: apt name=swi-prolog state=installed update_cache=no install_recommends=no

    - name: install doxygen
      action: apt pkg={{item}} state=installed install_recommends=no update_cache=no
      with_items:
        - doxygen
	- graphviz

    - include: tasks/installjavatests.yml
