---
  - hosts: a445
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a445/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"

    - name: install packages for gss api auth to work
      action: apt pkg={{item}} state=installed install_recommends=no update_cache=yes
      with_items:
        - libsasl2-modules-gssapi-mit
        - libncurses5:i386

    - include: tasks/installcodeblocks.yml
    - include: tasks/fix_meltdown.yml
    
    - name: install netbeans
      action: apt name=netbeans state=latest install_recommends=no update_cache=no
    
    - name: install maxima-share
      action: apt name=maxima-share state=latest install_recommends=no update_cache=no
    - name: install latest firefox
      action: apt name=firefox-esr state=latest install_recommends=no update_cache=no

    - name: install php5-mysql
      action: apt name=php5-mysql state=present install_recommends=no update_cache=no

    - include: tasks/copyansiblehosts.yml
    - include: tasks/add_permission_read_logs_apache2.yml
    - include: tasks/installhaskell.yml
    - include: tasks/installsmartgit.yml
    - include: tasks/installstatusreport.yml
    - include: tasks/addunburden-home.yml
    - include: tasks/installwebstormclion.yml
    - include: tasks/install_arm_toolchain.yml
    - include: tasks/fixxsessionerrors.yml
    - include: tasks/installvnc.yml
    - include: tasks/installrusersd.yml
    - include: tasks/installnscd.yml
    - include: tasks/installcollectd.yml
    - include: tasks/addscratch.yml
      vars:
        volume_group: "a445"

  - hosts: a439
    remote_user: root
    tasks:
    - include: tasks/installcodeblocks.yml
    - include: tasks/fix_meltdown.yml
    - name: install php5-mysql
      action: apt name=php5-mysql state=present install_recommends=no update_cache=no
    - name: install maxima-share
      action: apt name=maxima-share state=latest install_recommends=no update_cache=no
    - name: install latest firefox
      action: apt name=firefox-esr state=latest install_recommends=no update_cache=no

    - include: tasks/copyansiblehosts.yml
    - include: tasks/add_permission_read_logs_apache2.yml
    - include: tasks/installstatusreport.yml
    - include: tasks/installhaskell.yml
    - include: tasks/installsmartgit.yml
    - include: tasks/addunburden-home.yml
    - include: tasks/installwebstormclion.yml
    - include: tasks/installjavatests.yml
    - include: tasks/installnscd.yml
    - include: tasks/installcollectd.yml
    - include: tasks/addscratch.yml
      vars:
        volume_group: "a515"
  
  - hosts: a437
    remote_user: root
    tasks:
    - include: tasks/installcodeblocks.yml
    - include: tasks/fix_meltdown.yml
    
    - name: install php5-mysql
      action: apt name=php5-mysql state=present install_recommends=no update_cache=no
    - name: install maxima-share
      action: apt name=maxima-share state=latest install_recommends=no update_cache=no
    - name: install latest firefox
      action: apt name=firefox-esr state=latest install_recommends=no update_cache=no

    - include: tasks/copyansiblehosts.yml
    - include: tasks/add_permission_read_logs_apache2.yml
    - include: tasks/installstatusreport.yml
    - include: tasks/installhaskell.yml
    - include: tasks/installsmartgit.yml
    - include: tasks/addunburden-home.yml
    - include: tasks/installnscd.yml
    - include: tasks/installcollectd.yml
    - include: tasks/addscratch.yml
      vars:
        volume_group: "a437"
  
  - hosts: a443
    remote_user: root
    tasks:
    - include: tasks/installcodeblocks.yml
    - include: tasks/fix_meltdown.yml
    
    - name: install php5-mysql
      action: apt name=php5-mysql state=present install_recommends=no update_cache=no
    - name: install maxima-share
      action: apt name=maxima-share state=latest install_recommends=no update_cache=no
    - name: install latest firefox
      action: apt name=firefox-esr state=latest install_recommends=no update_cache=no

    - name: setup scanner
      action: lineinfile dest=/etc/sane.d/xerox_mfp.conf state=present line="tcp a517mfu 9400"
    
    - name: setup scanner
      action: lineinfile dest=/etc/sane.d/xerox_mfp.conf state=absent line="tcp a517mfu2 9400"

    - include: tasks/copyansiblehosts.yml
    - include: tasks/addunburden-home.yml
    - include: tasks/installhaskell.yml
    - include: tasks/installsmartgit.yml
    - include: tasks/installstatusreport.yml
    - include: tasks/installwebstormclion.yml
    - include: tasks/installnscd.yml
    - include: tasks/installcollectd.yml
    - include: tasks/addscratch.yml
      vars:
        volume_group: "a443"
    
  - hosts: a441
    remote_user: root
    tasks:
    - name: setup scanner
      action: lineinfile dest=/etc/sane.d/xerox_mfp.conf state=present line="tcp a517mfu2 9400"
    
    - name: setup scanner2
      action: lineinfile dest=/etc/sane.d/xerox_mfp.conf state=absent line="tcp a517mfu 9400"
    
    - include: tasks/installcodeblocks.yml
    - include: tasks/fix_meltdown.yml
    
    - name: install php5-mysql
      action: apt name=php5-mysql state=present install_recommends=no update_cache=no
    - name: install maxima-share
      action: apt name=maxima-share state=latest install_recommends=no update_cache=no
    - name: install latest firefox
      action: apt name=firefox-esr state=latest install_recommends=no update_cache=no
    
    - include: tasks/copyansiblehosts.yml
    - include: tasks/installstatusreport.yml
    - include: tasks/installhaskell.yml
    - include: tasks/installsmartgit.yml
    - include: tasks/addunburden-home.yml
    - include: tasks/installwebstormclion.yml
    - include: tasks/installjavatests.yml
    - include: tasks/installnscd.yml
    - include: tasks/installcollectd.yml
    - include: tasks/addscratch.yml
      vars:
        volume_group: "a441"
    
  - hosts: termserver.dcti.sut.ru
    remote_user: root
    tasks:
    
    - include: tasks/copyansiblehosts.yml
    - include: tasks/installcodeblocks.yml
    - include: tasks/installstatusreport.yml
    - include: tasks/fix_meltdown.yml
    
    - name: install php5-mysql
      action: apt name=php5-mysql state=present install_recommends=no update_cache=no
    - name: install maxima-share
      action: apt name=maxima-share state=latest install_recommends=no update_cache=no
    - name: install latest firefox
      action: apt name=firefox-esr state=latest install_recommends=no update_cache=no

    - include: tasks/addunburden-home.yml
    - include: tasks/installhaskell.yml
    - include: tasks/installsmartgit.yml
    - include: tasks/installwebstormclion.yml
    - include: tasks/installnscd.yml
    - include: tasks/installcollectd.yml
    - include: tasks/addscratch.yml
      vars:
        volume_group: "a443"
