---
  - hosts: all
    remote_user: root
    tasks: 
    - include: tasks/copyansiblehosts.yml
    - name: install lm-sensors
      action: apt name=lm-sensors state=present install_recommends=no update_cache=no
    - name: install libpng12 for quartus
      action: apt name=libpng12-0 state=present install_recommends=no update_cache=no

  - hosts: classes
    remote_user: root
    tasks:
    - include: tasks/fix_apt_repos.yml
    - include: tasks/addstretchbackports.yml
    - include: tasks/aptgetupdate.yml
    - include: tasks/updatetimezone.yml
    - include: tasks/create_rc_local.yml
    - include: tasks/installdebiankeyring.yml
    - include: tasks/logrotate.yml
    - include: tasks/installstatusreport.yml
    - include: tasks/addunburden-home.yml
    - include: tasks/fix_meltdown.yml
    - include: tasks/installcodeblocks.yml
    - include: tasks/fix_autofs_systemd.yml
    - name: install latest firefox
      action: apt name=firefox-esr state=latest install_recommends=no update_cache=no
    - name: install qemu-system
      action: apt pkg={{item}} state=installed install_recommends=no update_cache=no
      with_items:
        - qemu-system
        - qemu-kvm
    - include: tasks/install_maxima.yml
    - include: tasks/installsmartgit.yml
    - include: tasks/installwebstormclion.yml
    - include: tasks/installidea.yml
    - include: tasks/installhaskell.yml
    - include: tasks/installcollectd.yml
    - include: tasks/installnscd.yml
    - include: tasks/install_php5mysql.yml
    - include: tasks/install_internet.yml
    - include: tasks/install_localca.yml
    - include: tasks/install_netbeans.yml

  - hosts: a445
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a445/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - name: install packages for gss api auth to work
      action: apt pkg={{item}} state=installed install_recommends=no update_cache=no
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '7'
      with_items:
        - libsasl2-modules-gssapi-mit
        - libncurses5:i386
    - include: tasks/add_permission_read_logs_apache2.yml
    - include: tasks/install_arm_toolchain.yml
    - include: tasks/fixxsessionerrors.yml
    - include: tasks/installvnc.yml
    - include: tasks/install_quartus_15.yml
    - include: tasks/fix_access_mysql.yml
  - hosts: a439
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a439/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - include: tasks/add_permission_read_logs_apache2.yml
    - include: tasks/installjavatests.yml
    - include: tasks/install_quartus_15.yml
    - include: tasks/fix_access_mysql.yml
  
  - hosts: a437
    remote_user: root
    tasks:
    - name: install mate desktop
      action: apt pkg=mate-desktop-environment state=installed update_cache=no
    - include: tasks/installlightdmback.yml
    - include: tasks/addlocalrepo.yml
    - name: deploy admin access
      copy: src=files/a439/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - include: tasks/add_permission_read_logs_apache2.yml
    - include: tasks/fix_access_mysql.yml
    handlers:
      - include: handlers/restartmysql.yml
       
  - hosts: a443
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a443/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - name: setup scanner
      action: lineinfile dest=/etc/sane.d/xerox_mfp.conf state=present line="tcp a517mfu 9400"
    - name: setup scanner
      action: lineinfile dest=/etc/sane.d/xerox_mfp.conf state=absent line="tcp a517mfu2 9400"
    - name: install sane-utils
      action: apt pkg=sane-utils state=installed install_recommends=no update_cache=no
    
  - hosts: a441
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a441/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - name: setup scanner
      action: lineinfile dest=/etc/sane.d/xerox_mfp.conf state=absent line="tcp a517mfu2 9400"
    - name: setup scanner2
      action: lineinfile dest=/etc/sane.d/xerox_mfp.conf state=present line="tcp a517mfu 9400"
    - name: install sane-utils
      action: apt pkg=sane-utils state=installed install_recommends=no update_cache=no
    - include: tasks/installjavatests.yml
    
  - hosts: termserver.dcti.sut.ru
    remote_user: root
    tasks:
    - include: tasks/install_quartus_15.yml
    - name: deploy admin access
      copy: src=files/a441/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
