---
  - hosts: all
    remote_user: root
    tasks:
#    - name: apt update
#      action: apt update_cache=yes
    - include: tasks/copyansiblehosts.yml

# Labs where no remote access is used
  - hosts: noremote
    remote_user: root
    tasks:
    - include: tasks/installlightdmback.yml
    - name: add pam group config
      copy: src=files/a441/etc/security/group.conf dest=/etc/security/group.conf owner=root group=distrib mode="0664"

# All classes, including terminal server
  - hosts: classes
    remote_user: root
    tasks:
    - include: tasks/install_latest_backports_kernel.yml
    - include: tasks/install_tablet_support.yml
    - include: tasks/install_dosemu.yml
    - include: tasks/updatetimezone.yml
    - include: tasks/installdebiankeyring.yml
    - include: tasks/installstatusreport.yml
    - include: tasks/addunburden-home.yml
    - include: tasks/installcodeblocks.yml
    - name: install latest firefox
      action: apt name=firefox-esr state=latest install_recommends=no update_cache=no
    - name: install latest chromium
      action: apt name={{item}} state=latest install_recommends=no update_cache=no
      with_items:
        - chromium
        - chromium-l10n
    - name: install nfs4-acl-tools
      action: apt name=nfs4-acl-tools state=present install_recommends=no update_cache=no
    - include: tasks/installidea.yml
    - include: tasks/install_php5mysql.yml
    - include: tasks/install_internet.yml
    - include: tasks/install_localca.yml
    - include: tasks/install_netbeans.yml
    - include: tasks/install_pycharm.yml
    - include: tasks/autostart_pidgin.yml
    - include: tasks/add_permission_read_logs_apache2.yml
    - include: tasks/install_unattended_upgrades.yml
    - include: tasks/enable_quota_applet.yml
    - name: remove sudo
      action: apt pkg=sudo state=absent update_cache=no
    - name: install convenience tools
      action: apt name={{item}} state=installed install_recommends=no update_cache=no
      with_items:
        - htop
        - screen
        - dvtm
        - splitvt
        - pbzip2
        - pigz
    - name: update kerberos configs
      copy: src=files/common/etc/krb5.conf dest=/etc/krb5.conf owner=root group=root mode="0644"

  - hosts: a445
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a445/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - include: tasks/install_vmshortcuts.yml

  - hosts: a439
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a439/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - include: tasks/install_vmshortcuts.yml
  
  - hosts: a437
    remote_user: root
    tasks:
    - include: tasks/addlocalrepo.yml
    - name: deploy admin access
      copy: src=files/a439/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    handlers:
      - include: handlers/restartmysql.yml
 
  - hosts: a443
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a443/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    
  - hosts: a441
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a441/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    
  - hosts: termserver.dcti.sut.ru
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a441/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - include: tasks/autostart_pidgin.yml
  
  - hosts: termserver2.dcti.sut.ru
    remote_user: root
    tasks:
    - name: deploy admin access
      copy: src=files/a441/root/.k5login dest=/root/.k5login owner=root group=root mode="0644"
    - include: tasks/autostart_pidgin.yml

  - hosts: remoteteaching
    remote_user: root
    tasks:
    - name: install discord
      action: apt pkg=discord state=latest install_recommends=no update_cache=no
    - name: install zoom
      action: apt pkg=zoom state=latest install_recommends=no update_cache=no
  - hosts: remoteprinters
    remote_user: root
    tasks:
    - include: tasks/add_remote_printer_access.yml
