   - name: Add local PIVT repo to machine
     action: apt_key data="{{ lookup('file', 'apt.gpg') }}" state=present
     action: apt_repository repo='deb http://apt.dcti.sut.ru/debian/ bonch essential' state=absent
     action: apt_repository repo='deb http://apt.dcti.sut.ru/debian/ bonch main' state=present
