    - name: enable quota applet
      action: apt pkg={{ item }} state=latest
      with_items:
       - quota-applet

    - name: Add quota-applet to autostart
      copy:
        src: /usr/share/applications/quota-applet.desktop
        dest: /etc/xdg/autostart/
        mode: 0755
        remote_src: yes
