    - name: enable quota applet
      apt:
        pkg: quota-applet
        state: latest

    - name: Add quota-applet to autostart
      copy:
        src: /usr/share/applications/quota-applet.desktop
        dest: /etc/xdg/autostart/
        mode: 0755
        remote_src: yes
