   - name: list files
     shell: "vgdisplay -c|head -n 1|awk -F: '{print $1}'|sed 's/^ *//g'"
     register: vgname

   - name: Unmount /home
     when: vgname.stdout != ""
     action: mount name=/home src=/dev/mapper/{{ vgname.stdout }}-home state=absent

   - name: Delete home volume
     when: vgname.stdout != ""
     action: lvol vg={{ vgname.stdout }} lv=home state=absent force=yes

   - name: Resize root
     when: vgname.stdout != ""
     action: lvol vg={{ vgname.stdout }} lv=root state=present size=35g resizefs=yes shrink=no force=yes

   - name: Resize var
     when: vgname.stdout != ""
     action: lvol vg={{ vgname.stdout }} lv=var state=present size=10g resizefs=yes shrink=no force=yes

   - name: Resize tmp
     when: vgname.stdout != ""
     action: lvol vg={{ vgname.stdout }} lv=tmp state=present size=10g resizefs=yes shrink=no force=yes

   - name: Add opt lvm location
     when: vgname.stdout != ""
     action: lvol vg={{ vgname.stdout }} lv=opt size=40g shrink=no

   - name: Make filesystem on opt volume
     when: vgname.stdout != ""
     action: filesystem fstype=ext4 dev=/dev/mapper/{{ vgname.stdout }}-opt

   - name: Add opt to fstab
     when: vgname.stdout != ""
     action: mount name=/opt src=/dev/mapper/{{ vgname.stdout }}-opt state=mounted fstype=ext4

