    - name: install netbeans
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9']
      action: apt pkg=netbeans state=latest install_recommends=no
    - name: install netbeans
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['10']
      action: apt pkg=netbeans state=latest install_recommends=no
