    - name: install browsers
      apt:
        pkg:
         - firefox-esr
         - chromium
         - chromium-l10n
         - netsurf-gtk
         - elinks
         - w3m
         - lynx
        state: installed
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9','10']
    - name: install google chrome
      apt:
        pkg:
         - google-chrome-stable
        state: installed
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['10']
