    - name: install rust
      apt:
        pkg:
         - rustc
         - cargo
         - rust-gdb
         - rust-doc
        state: installed
        install_recommends: no
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9', '10']

