    - name: install lisp
      action: apt pkg={{item}} state=installed
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'
      with_items:
       - cl-launch
       - sbcl
#       - clisp
#       - clisp-module-\*

    - name: install lisp
      action: apt pkg={{item}} state=installed
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '7'
      with_items:
       - clisp
       - clisp-module-\*
