    - name: install php5-mysql
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '7'
      action: apt name=php5-mysql state=present install_recommends=no update_cache=no
