   - name: Add key for monodevelop repo to machine
     action: apt_key url=http://apt.dcti.sut.ru/monodevelop.gpg state=present
     when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10'

   - name: Add new repo for monodevelop
     when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10'
     action: apt_repository repo='deb http://download.mono-project.com/repo/debian vs-buster main' state=present

   - name: install monodevelop
     apt: pkg=monodevelop state=present update_cache=yes
     when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10'
