    - name: install terminus fonts
      apt:
        pkg:
          - xfonts-terminus
          - xfonts-terminus-oblique
          - xfonts-terminus-dos
        state: present
        install_recommends: no
        update_cache: no
