    - name: install browsers
      apt:
        pkg:
         - firefox-esr
         - chromium
         - chromium-l10n
         - netsurf-gtk
        state: installed
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9','10']
