    - name: install verilog
      apt:
        pkg:
         - gtkwave
         - iverilog
        state: installed
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9', '10','11']
