    - name: install qtsdk
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['10']
      apt:
        pkg:
         - qt5-default
         - qtcreator
         - qt5-doc
         - qt5-doc-html
         - qmlscene
         - qtbase5-dev-tools
         - qtbase5-dev
         - qtbase5-private-dev
         - qtdeclarative5-dev
         - qtscript5-dev
         - qtdeclarative5-dev-tools
         - qttools5-dev-tools
         - qttools5-dev
         - qtxmlpatterns5-dev-tools
         - cmake
         - subversion
         - make
         - gdb
        state: installed
        install_recommends: no

    - name: install qtsdk
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9']
      apt:
        pkg:
         - qt-sdk
         - qt5-default
        state: installed
        install_recommends: no
