    - name: install pycharm
      action: apt name=pycharm state=latest update_cache=no
    - name: install virtualenvironment
      action: apt name={{item}} state=present update_cache=no
      with_items:
        - python-virtualenv
	- python3-virtualenv
	- virtualenv
