    - name: install xournal mypaint and xinput
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9', '10']
      apt:
        pkg:
         - xournal
         - xinput
         - mypaint
        state: installed
        install_recommends: no
    - name: install latests libwacom2 and utilities (for tablet settings)
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9', '10']
      apt:
        pkg:
         - libwacom2
         - libwacom-bin
        state: latest
        install_recommends: no
    - name: copy configuration files
      action: copy src=files/common/usr/share/X11/xorg.conf.d/71-wacom.conf dest=/usr/share/X11/xorg.conf.d/71-wacom.conf owner=root group=root mode=0644
