    - name: install libreoffice
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9', '10','11']
      apt:
        pkg:
         - libreoffice
         - libreoffice-base
         - libreoffice-calc
         - libreoffice-draw
         - libreoffice-help-ru
         - libreoffice-l10n-ru
         - libreoffice-impress
         - libreoffice-math
         - libreoffice-writer
         - libreoffice-nlpsolver
         - libreoffice-pdfimport
        state: installed
    - name: install libreoffice lightproof
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version in ['9','11']
      apt:
        pkg:
         - libreoffice-lightproof-ru-ru
        state: installed
