    - name: install inetd
      apt:
        pkg: inetutils-inetd
        state: present
        install_recommends: no
    - name: install atftpd
      apt:
        pkg: atftpd
        state: present
        install_recommends: no
    - name: make directory for boot files
      file:
        path: '/opt/tftpboot'
        state: directory
    - name: remove old directory for boot files
      file:
        path: '/srv/tftp'
        state: absent
    - name: deploy line into /etc/inetd.conf
      lineinfile:
        state: present
        line: 'tftp     dgram   udp4    wait    nobody /usr/sbin/tcpd /usr/sbin/in.tftpd --tftpd-timeout 300 --retry-timeout 5 --mcast-port 1758 --mcast-addr 239.239.239.0-255 --mcast-ttl 1 --maxthread 100 --verbose=5 /opt/tftpboot'
        path: /etc/inetd.conf
